//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Active_Directory_Management.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Addresses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Addresses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Active_Directory_Management.Properties.Addresses", typeof(Addresses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC=nng,DC=kz.
        /// </summary>
        internal static string AktauDomain {
            get {
                return ResourceManager.GetString("AktauDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU=Users,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string AktauUsers {
            get {
                return ResourceManager.GetString("AktauUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC=ala,DC=nng,DC=kz.
        /// </summary>
        internal static string AlmatyDomain {
            get {
                return ResourceManager.GetString("AlmatyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU=Users,OU=Almaty,DC=ala,DC=nng,DC=kz.
        /// </summary>
        internal static string AlmatyUsers {
            get {
                return ResourceManager.GetString("AlmatyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC=msq,DC=nng,DC=kz.
        /// </summary>
        internal static string MinskDomain {
            get {
                return ResourceManager.GetString("MinskDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU=Users,OU=Minsk,DC=msq,DC=nng,DC=kz.
        /// </summary>
        internal static string MinskUsers {
            get {
                return ResourceManager.GetString("MinskUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC=ura,DC=nng,DC=kz.
        /// </summary>
        internal static string UralskDomain {
            get {
                return ResourceManager.GetString("UralskDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU=Users,OU=Uralsk,DC=ura,DC=nng,DC=kz.
        /// </summary>
        internal static string UralskUsers {
            get {
                return ResourceManager.GetString("UralskUsers", resourceCulture);
            }
        }
    }
}
