//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Active_Directory_Management.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Groups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Groups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Active_Directory_Management.Properties.Groups", typeof(Groups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=bitrixusersgroupSCO,OU=Users,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string BitrixUsers {
            get {
                return ResourceManager.GetString("BitrixUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=SEC-OwnCloudAccess,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=ESET DVD Drives Allowed,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string DvdDrives {
            get {
                return ResourceManager.GetString("DvdDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=External Mail Users,OU=Microsoft Exchange,OU=Groups,DC=nng,DC=kCN=External Mail Users,OU=Microsoft Exchange,OU=Groups,DC=nng,DC=kz.
        /// </summary>
        internal static string ExternalMail {
            get {
                return ResourceManager.GetString("ExternalMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=SEC-Aktau-HomeFolder,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string HomeFolder {
            get {
                return ResourceManager.GetString("HomeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=FullAccess,OU=InternetAccess,OU=Groups,DC=nng,DC=kz.
        /// </summary>
        internal static string InternetFull {
            get {
                return ResourceManager.GetString("InternetFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=LimitedAccess,OU=InternetAccess,OU=Groups,DC=nng,DC=kz.
        /// </summary>
        internal static string InternetLimited {
            get {
                return ResourceManager.GetString("InternetLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=APP-OutlookSignature,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string OutlookSignature {
            get {
                return ResourceManager.GetString("OutlookSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=ESET USB Mobile Devices Allowed,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string UsbDevices {
            get {
                return ResourceManager.GetString("UsbDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=ESET USB Drives Allowed,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string UsbDrives {
            get {
                return ResourceManager.GetString("UsbDrives", resourceCulture);
            }
        }
    }
}
