//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Active_Directory_Management.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Active_Directory_Management.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string addresses {
            get {
                return ResourceManager.GetString("addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=ESET DVD Drives Allowed,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string cdGroup {
            get {
                return ResourceManager.GetString("cdGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string cloudGroup {
            get {
                return ResourceManager.GetString("cloudGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.xml.
        /// </summary>
        internal static string db_filename {
            get {
                return ResourceManager.GetString("db_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://OU=Users,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string devAddr {
            get {
                return ResourceManager.GetString("devAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC=nng,DC=kz.
        /// </summary>
        internal static string domain {
            get {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=FullAccess,OU=InternetAccess,OU=Groups,DC=nng,DC=kz.
        /// </summary>
        internal static string internetFullAccessGroup {
            get {
                return ResourceManager.GetString("internetFullAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=LimitedAccess,OU=InternetAccess,OU=Groups,DC=nng,DC=kz.
        /// </summary>
        internal static string internetLimitedAccessGroup {
            get {
                return ResourceManager.GetString("internetLimitedAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://OU=Users,OU=Uralsk,DC=ura,DC=nng,DC=kz.
        /// </summary>
        internal static string uradevAddr {
            get {
                return ResourceManager.GetString("uradevAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=ESET USB Mobile Devices Allowed,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string usbDeviceGroup {
            get {
                return ResourceManager.GetString("usbDeviceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN=ESET USB Drives Allowed,OU=Groups,OU=Aktau,DC=nng,DC=kz.
        /// </summary>
        internal static string usbDiskGroup {
            get {
                return ResourceManager.GetString("usbDiskGroup", resourceCulture);
            }
        }
    }
}
